### ISSUE TITLE
Problem after npm start

### ISSUE THREAD

**Issue by filippini91** [arkalim/kindle-to-notion#10]
Hey Abdur, great work and a great idea. However it seems there's a problem when I run npm start, the highlights are not syncing, I think the problem is on my side, but I'm not very good at coding so I can't figure it out. Could you help me out?

Attaching the terminal log.

Thanks, Marek

[terminal.txt](https://github.com/arkalim/kindle-to-notion/files/9689965/terminal.txt)

**Comment by mikaal46** [comment]
Hi Marek,

It turns out that you have about 110 highlights in one of your books, The Almanack of Naval Ravikant: A Guide to Wealth and Happiness, but this program allows only 100 at a time.

I had a similar problem and I also know very little about coding. But don’t worry, there’s a work around.

What you can do is open your My Clippings.txt and select 10 of the highlights from that book and cut and paste them somewhere else. Then, try npm start and it will sync the 100 highlights. Then you can copy those 10 highlights back in to your My Clippings.txt and npm start again. It should have no problem syncing the new 10 highlights. The problem happens when there are more than 100 “new” highlights.

Let me know if it works.

Best,
Meekal

**Comment by filippini91** [comment]
Thanks Meekal, worked like charm! Have a good day 🙏
